[mosaic_dataloader]
name = "streaming"
# Location of the streamed shards.
remote = "s3://smollm-corpus/shared"
# Local cache directory used by streaming.
local = "smollm-corpus/shared"
# Dataset split to consume.
split = "train"
shuffle = true
max_seq_len = 128

# Streams for the smollm-corpus dataset
[[mosaic_dataloader.streams]]
remote = "fineweb_edu_dedup/client_0"
local = "fineweb_edu_dedup/client_0"
proportion = 70

[[mosaic_dataloader.streams]]
remote = "fineweb_edu_dedup/client_1"
local = "fineweb_edu_dedup/client_1"
proportion = 70

[[mosaic_dataloader.streams]]
remote = "fineweb_edu_dedup/client_2"
local = "fineweb_edu_dedup/client_2"
proportion = 70

[[mosaic_dataloader.streams]]
remote = "fineweb_edu_dedup/client_3"
local = "fineweb_edu_dedup/client_3"
proportion = 70

[[mosaic_dataloader.streams]]
remote = "fineweb_edu_dedup/client_4"
local = "fineweb_edu_dedup/client_4"
proportion = 70

[[mosaic_dataloader.streams]]
remote = "fineweb_edu_dedup/client_5"
local = "fineweb_edu_dedup/client_5"
proportion = 70

[[mosaic_dataloader.streams]]
remote = "fineweb_edu_dedup/client_6"
local = "fineweb_edu_dedup/client_6"
proportion = 70

[[mosaic_dataloader.streams]]
remote = "fineweb_edu_dedup/client_7"
local = "fineweb_edu_dedup/client_7"
proportion = 70