[mosaic_dataloader]
name = "mosaic_streaming"
# Location of the streamed shards. Supports any URI that Mosaic Streaming can read.
remote = "s3://my-bucket/path/to/shards"
# Local cache directory used by streaming.
local = "/tmp/mosaic-cache"
# Dataset split to consume.
split = "train"
# Optional: proportion of samples pulled from each stream.
# Delete the [[streams]] tables if you only rely on the default stream.

[[mosaic_dataloader.streams]]
remote = "s3://my-bucket/path/to/shards/train"
local = "/tmp/mosaic-cache/train"
proportion = 1.0