[job]
description = "Llama 3 debug training with Mosaic streaming"

[model]
name = "llama3_mosaic"
flavor = "debugmodel"
hf_assets_path = "tests/assets/tokenizer"

[optimizer]
lr = 8e-4
beta1 = 0.9
beta2 = 0.95
weight_decay = 0.1
implementation = "fused"

[training]
steps = 10
local_batch_size = 2
seq_len = 128
seed = 17
# Mosaic streaming parameters live in mosaic_dataloader.toml.

[metrics]
log_freq = 1

[checkpoint]
enable = false
