# torchtitan Config.toml
# NOTE: this toml config is a preset for 128 H100 GPUs.

[job]
dump_folder = "./outputs"
description = "Llama 3 405B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama3"
flavor = "405B"
tokenizer_path = "./assets/tokenizer/Llama-3.1-8B"
converters = ["float8"]

[optimizer]
name = "AdamW"
lr = 8e-5
eps = 1e-8

[lr_scheduler]
warmup_steps = 600  # lr scheduler warm up, normally 20% of the train steps

[training]
local_batch_size = 1
seq_len = 8192
max_norm = 1.0  # grad norm clipping
steps = 3000
compile = true
dataset = "c4"

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1  # 8-way TP
enable_async_tensor_parallel = true
pipeline_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "hf__checkpoint"
interval = 500
last_save_model_weights_only = true
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]
last_save_in_safetensors_format = false
initial_load_model_weights_only = true
# initial_load_path = "outputs/Llama-3.1-8B/consolidated/"
# initial_load_path = "/home/ankitageorge/tmp/mffuse/8b-safetensors/consolidated/"
# initial_load_path = "/home/ankitageorge/tmp/mffuse/8b-dcp/"
# initial_load_path = "outputs/checkpoint/step-6"
# initial_load_path = "outputs/hf_checkpoint/step-5"
# initial_load_path = "/home/ankitageorge/ankita_test_bucket/tree/8b-dcp"
# initial_load_path = "/home/ankitageorge/ankita_test_bucket/tree/8b-safetensors/consolidated/"
initial_load_path = "/mnt/mffuse2/tree/405b-hf/"
# initial_load_path = "/data/users/ankitageorge/8b-hf/"
initial_load_in_hf = true

[activation_checkpoint]
mode = "full" # ["none", "selective", "full"]

[float8]
enable_fsdp_float8_all_gather = true
precompute_float8_dynamic_scale_for_fsdp = true
filter_fqns = ["output"]
